# Use the official .NET Core SDK image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["./app/Gantt/Gantt.csproj", "./"]

# Add the necessary NuGet packages
RUN dotnet add package Npgsql --version 7.0.0
RUN dotnet add package Dapper --version 2.0.123

RUN dotnet restore "./Gantt.csproj"
COPY ./app/Gantt/ .
WORKDIR "/src/."
RUN dotnet build "Gantt.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Gantt.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Gantt.dll"]
