name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build --file Dockerfile.dotnet --tag gantt:latest .
    - name: Login to ECR
      id: ecr
      uses: jwalton/gh-ecr-login@v3
      with:
        access-key-id: "AKIATCKANDJX7LAGHE7W"
        secret-access-key: "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"
        region: us-east-1
    - name: Tag the Docker image for ECR
      run: docker tag gantt:latest ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/gantt:latest
    - name: Push to ECR
      run: |
        docker push ${{ steps.ecr.outputs.account }}.dkr.ecr.us-east-1.amazonaws.com/gantt:latest
